name: Run tests for all PRs
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Code
        id: git-checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: pixl8/github-action-box-test@v3
        with:
          test_server_json: /server.json
          output_file: /tests/test-results.txt
          verbose: false
